# Generated by Django 2.0.2 on 2018-04-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('isBooked', models.BooleanField(default=False)),
                ('charge', models.CharField(max_length=100)),
                ('parentParking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Parking')),
            ],
        ),
    ]
