# Generated by Django 2.0.2 on 2018-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.AlterField(
            model_name='parking',
            name='pid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='sid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
