# Generated by Django 2.0.2 on 2018-04-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='isBooked',
        ),
    ]
