# Generated by Django 2.0.2 on 2018-04-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_slot_isbooked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('parentSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=True)),
                ('bookedForDate', models.CharField(max_length=100)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AppUser')),
                ('subSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubSlot')),
            ],
        ),
    ]
