# Generated by Django 2.0.2 on 2018-04-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subslot_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=100)),
                ('vtype', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AppUser')),
            ],
        ),
    ]
